---
- hosts: solr
  become: true 
  vars_files:
    - vars.yml
  pre-tasks:
    - name: update cache if needed
      yum: update_cache=true cache_valid_time=3600

  handlers:
    - name: restart solr
      service: name=solr state=restarted

  tasks:  
    - name: install Java (pre-req for solr)
      yum: name=openjdk-8-jdk state=present
    - name: Download Solr
      get_url:
        url: https://www.apache.org/dyn/closer.lua/solr/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz?action=download
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
